language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lukaromih/react-test -f client/Dockerfile.dev client

script:
  - docker run -e CI=true lukaromih/react-test npm run test

after_success:
  - docker build -t lukaromih/multi-client client
  - docker build -t lukaromih/multi-nginx nginx
  - docker build -t lukaromih/multi-server server
  - docker build -t lukaromih/multi-worker worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push lukaromih/multi-client
  - docker push lukaromih/multi-nginx
  - docker push lukaromih/multi-server
  - docker push lukaromih/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-368661070039
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
